#!/bin/bash -v
swig -c++ -java fact.i
g++ -c -fPIC stuff.cpp
g++ -fPIC -I /usr/lib/jvm/java-6-openjdk/include -I /usr/lib/jvm/java-6-openjdk/include/linux -c fact_wrap.cxx
ld -G *.o -o libtest.so
export LD_LIBRARY_PATH=/home/sunil/swig-java/one/:$LD_LIBRARY_PATH
javac *.java
java runme
