#!/bin/bash -v 
git clean -xfd
mkdir build;
cd build;

cmake ../src
#cmake --trace --debug-output ../src/;
make install VERBOSE=1;
cd ..;
lein2 javac
eu-readelf -a cpp_lib/libmisc_utils_java.so | egrep fact
lein2 swank
